export const publishers = ["1517 Media",
"37 INK",
"A",
"A & C Black",
"A. C. McClurg",
"A. S. Barnes & Co.",
"Abilene Christian University Press",
"Ablex Publishing",
"Abrams Books",
"Academic Press",
"Ace Books",
"Addison-Wesley",
"Adis International",
"Airiti Press",
"Akashic Books",
"Aladdin Paperbacks",
"Alfred A. Knopf",
"Allen & Unwin",
"Allison & Busby",
"Alma Books",
"Alyson Books",
"American Graphics Institute",
"André Deutsch",
"Andrews McMeel Publishing",
"Anova Books",
"Antenne Books",
"Anvil Press Poetry",
"Applewood Books",
"Apress",
"Arbor House",
"Arbordale Publishing",
"Arcade Publishing",
"Arcadia Publishing",
"Arkham House",
"Arktos Media",
"Armida Publications",
"ArtScroll",
"Ash-Tree Press",
"Athabasca University Press",
"Atheneum Books",
"Atheneum Publishers",
"Atlantic Books",
"Atlas Press",
"ATOM Books",
"Atria Publishing Group",
"Aunt Lute Books",
"Austin Macauley Publishers",
"Avery Publishing - an imprint of the Penguin Group",
"Avon Publications",
"Baen Books",
"Baker Publishing Group",
"Ballantine Books",
"Banner of Truth Trust",
"Bantam Books",
"Bantam Spectra",
"Bares & Noble Books",
"Barrie & Jenkins",
"Basic Books",
"BBC Books",
"Belknap Press",
"Bella Books",
"Bellevue Literary Press",
"Bendon Publishing International",
"Berg Publishers",
"Berkley Books",
"Bison Books",
"Black Dog Publishing",
"Black Ink Collective",
"Black Library",
"Black Sparrow Press",
"Black & White Publishing",
"Blackie and Son",
"Blackstaff Press",
"Blackwell Publishing",
"Blake Publishing",
"Bloodaxe Books",
"Bloomsbury Publishing",
"Blue Ribbon Books, Garden City, New York",
"Bobbs-Merrill Company",
"Bogle-L'Ouverture Publications",
"Book League of America",
"Book Works",
"Booktrope",
"Borgo Press",
"Boundless",
"Bowes & Bowes",
"Boydell & Brewer",
"Broadside Lotus Press",
"Breslov Research Institute",
"Brill Publishers",
"Brimstone Press",
"Broadview Press",
"Burns & Oates",
"Butterworth-Heinemann",
"Caister Academic Press UK",
"Cambridge University Press UK",
"Canadian Science Publishing",
"Candlewick Press",
"Canongate Books",
"Capstone Publishers",
"Carcanet Press, Manchester",
"Carlton Publishing Group UK",
"Carnegie Mellon University Press",
"Casemate Publishers",
"Cassava Republic Press",
"Cassell",
"Cengage",
"Central European University Press",
"Century",
"Chambers",
"Charles Scribner's Sons",
"Chatto & Windus",
"Chick Publications",
"Chronicle Books",
"Churchill Livingstone",
"Cisco Press",
"City Lights Publishers",
"Cloverdale Corporation",
"Cold Spring Harbor Laboratory Press",
"Collector's Guide Publishing",
"Collins",
"Columbia University Press",
"Concordia Publishing House",
"Constable & Co Ltd",
"Continuum International Publishing Group",
"Copper Canyon Press",
"Cork University Press",
"Cornell University Press",
"Coronet Books",
"Counterpoint",
"Craftsman Book Company",
"CRC Press",
"Creative Book Publishers International",
"Cresset Press",
"Crescent Books",
"Crocker & Brewster",
"Crown Publishing Group",
"D. Appleton & Company",
"D. Reidel",
"Da Capo Press",
"Dalkey Archive Press",
"David & Charles",
"DAW Books",
"Dedalus Books",
"Del Rey Books",
"Delacorte Press",
"Deseret Book Company",
"Dick & Fitzgerald",
"Directmedia Publishing",
"Disney Publishing Worldwide",
"DK",
"DNA Publications",
"Dobson Books",
"Dodd, Mead & Co.",
"Dorchester Publishing",
"Doubleday",
"Douglas & McIntyre",
"Dove Medical Press",
"Dover Publications",
"Dreamspinner Press",
"Dundurn Press",
"E. P. Dutton",
"Earthscan",
"ECW Press",
"Eel Pie Publishing",
"Elliot Stock",
"Ellora's Cave",
"Elsevier",
"Emerald Group Publishing",
"Etruscan Press",
"Europa Press",
"Everyman's Library",
"Ewha Womans University Press",
"Exact Change",
"Express Publishing",
"Faber and Faber",
"FabJob",
"Fairview Press",
"Fantagraphics Books",
"Farrar, Straus and Giroux",
"Felony & Mayhem Press",
"Firebrand Books",
"Flame Tree Publishing",
"Focal Press",
"Folio Society",
"Forum Media Group",
"Four Courts Press",
"Four Walls Eight Windows",
"Frederick Fell Publishers, Inc.",
"Frederick Warne & Co",
"Free Press",
"Fulcrum Press",
"Funk & Wagnalls",
"G. P. Putnam's Sons",
"G-Unit Books",
"Gaspereau Press",
"Gay Men's Press",
"Gefen Publishing House",
"George H. Doran Company",
"George Newnes",
"Godwit Press",
"Golden Cockerel Press",
"The Good Book Company (UK)",
"Good News Publishers",
"Goops Unlimited",
"Goose Lane Editions",
"Grafton",
"Graywolf Press",
"Greenery Press",
"Greenleaf Book Group",
"Greenleaf Publishing Ltd",
"Greenwillow Books",
"Greenwood Publishing Group",
"Gregg Press",
"Grosset & Dunlap",
"Grove Atlantic/Grove Press",
"Hachette Books, formerly Hyperion Books division of Disney Book Group, now a division of Perseus Books Group, a Hachette Book Group unit",
"Hachette Book Group USA",
"Hackett Publishing Company",
"Hamish Hamilton",
"Harbor Mountain Press",
"Harcourt Assessment",
"Harcourt",
"Harlequin Enterprises",
"Harper",
"Harper & Row",
"HarperCollins Publishers",
"HarperPrism",
"HarperTrophy",
"Harvard University Press",
"Harvest House",
"Harvill Press at Random House",
"Harvill Secker",
"Hawthorne Books",
"Hay House",
"Haynes Manual (UK)",
"Headline Publishing Group",
"Heinemann",
"Hesperus Press",
"Hemus",
"Heyday Books",
"HMSO",
"Hodder & Stoughton",
"Hogarth Press",
"Holland Park Press",
"Holt McDougal",
"Hoover Institution Press",
"Horizon Scientific Press (UK)",
"Houghton Mifflin Harcourt",
"House of Anansi Press",
"The House of Murky Depths (UK)",
"Howell-North Books",
"Humana Press",
"Hutchinson",
"Ian Allan Publishing",
"Ignatius Press",
"Indiana University Press",
"Influx Press",
"Informa",
"Information Age Publishing",
"Insomniac Press Canada",
"International Association of Engineers",
"International Universities Press",
"Inter-Varsity Press",
"InterVarsity Press",
"Ishi Press",
"Islamic Texts Society",
"Island Press",
"Ivyspring International Publisher",
"J. M. Dent",
"Jaico Publishing House",
"The Jarrold Group",
"The Jewish Publication Society",
"John Lane",
"John Murray",
"Jones & Bartlett Learning",
"Karadi Tales",
"Kensington Books",
"Kessinger Publishing",
"Kluwer Academic Publishers",
"Knockabout Comics",
"Kodansha",
"Kogan Page",
"Koren Publishers Jerusalem",
"Korero Press",
"KTAV Publishing House",
"Kumarian Press",
"Ladybird Books",
"Last Gasp",
"Leaf Books",
"Leafwood Publishers",
"Left Book Club",
"Legend Books",
"Legend Press",
"Lethe Press",
"Libertas Academica",
"Liberty Fund",
"Library of America",
"Lion Hudson",
"Lion Publishing",
"Lionel Leventhal",
"Lippincott Williams & Wilkins",
"Little, Brown and Company",
"Liverpool University Press",
"Llewellyn Worldwide",
"Longman",
"LPI Media",
"The Lutterworth Press",
"Macmillan Publishers",
"Mainstream Publishing",
"Manchester University Press",
"Mandrake of Oxford",
"Mandrake Press",
"Manning Publications",
"Manor House Publishing",
"Marion Boyars Publishers",
"Mark Batty Publisher",
"Marshall Cavendish",
"Marshall Pickering",
"Martinus Nijhoff Publishers",
"Matthias Media",
"McClelland & Stewart",
"McFarland & Company",
"McGraw-Hill Education",
"Medknow Publications",
"Melbourne University Publishing",
"Mercier Press",
"Methuen Publishing",
"Michael Joseph",
"Michael O'Mara Books",
"Michigan State University Press",
"Microsoft Press",
"The Miegunyah Press",
"Miles Kelly Publishing",
"Mills & Boon",
"Minerva Press",
"Mirage Publishing (UK)",
"MIT Press",
"Mkuki na Nyota",
"Modern Library",
"Morgan James Publishing",
"Mother Tongue Publishing",
"Mycroft & Moran",
"Myriad Editions",
"Naiad Press",
"Nauka",
"NavPress",
"New American Library",
"New Beacon Books",
"New Directions Publishing",
"New English Library",
"New Holland Publishers",
"New Village Press",
"New York Review Books",
"New Win Publishing",
"Newnes",
"No Starch Press",
"Nonesuch Press",
"Noontide Press",
"Northwestern University Press",
"Nosy Crow",
"Oberon Books",
"Open Book Publishers",
"Open Court Publishing Company",
"Open University Press",
"OR Books",
"Orchard Books",
"O'Reilly Media",
"Orion Books",
"Orion Publishing Group",
"Osprey Publishing",
"Other Press",
"The Overlook Press",
"Oxford University Press",
"Pacific Press Publishing Asssociation",
"Packt",
"Palgrave Macmillan",
"Pan Books",
"Pantheon Books",
"Papadakis Publisher",
"Parachute Publishing",
"Parragon",
"Pathfinder Press",
"Paulist Press",
"Pavilion Books",
"Pecan Grove Press",
"Pen and Sword Books",
"Pendleton Publishing",
"Penguin Books UK",
"Penguin Random House UK",
"Penn State University Press",
"Persephone Books",
"Perseus Books Group",
"Peter Lang",
"Peter Owen Publishers",
"Phaidon Press",
"Philosophy Documentation Center",
"Philtrum Press",
"Picador",
"Pimlico Books at Random House",
"Playwrights Canada Press",
"Pluto Press",
"Point Blank",
"Poisoned Pen Press",
"Policy Press",
"Polity",
"Practical Action",
"J. Q. Preble",
"Prentice Hall",
"Prime Books",
"Princeton University Press",
"Profile Books",
"Progress Publishers",
"Prometheus Books",
"Puffin Books",
"Purple House Press",
"Pushkin Press",
"Q",
"The Quarto Group",
"Que Publishing",
"Quebecor",
"Quirk Books",
"R",
"Random House",
"Red Circle Authors",
"Redstone Press",
"Reed Publishing",
"RELX",
"Remington & Co",
"Riverhead Books",
"Robert Hale",
"Robson Books",
"Rock Scorpion Books",
"Rodopi",
"Review and Herald",
"Routledge Kegan Paul",
"Rowman & Littlefield",
"Royal Society of Chemistry",
"S",
"S&P Global",
"SAGE Publishing",
"St. Martin's Press",
"Salt Publishing",
"Sams Publishing",
"Samuel French",
"Schocken Books",
"Scholastic Corporation",
"Scribner",
"Seagull Books",
"Serif",
"Shambhala Publications",
"Shire Books",
"Shuter & Shooter Publishers",
"Sidgwick & Jackson",
"Signet Books",
"Simon & Schuster",
"Sinclair-Stevenson",
"Society for Promoting Christian Knowledge",
"Sort of Books",
"Sounds True",
"Sourcebooks",
"South End Press",
"Spinsters Ink",
"Springer Science+Business Media (formally Springer Verlag)",
"Square One Publishers",
"Stanford University Press",
"The Stationery Office",
"Steidl",
"Stein and Day",
"Summerwild Productions",
"Summit Media",
"SUNY Press",
"T",
"T&T Clark",
"Tachyon Publications",
"Tammi, Finland",
"Target Books",
"Tarpaulin Sky Press",
"Tartarus Press",
"Tate Publishing & Enterprises",
"Taunton Press",
"Taylor & Francis",
"Ten Speed Press",
"Thames & Hudson (UK)",
"Thames & Hudson USA",
"Thieme Medical Publishers",
"Third World Press",
"Thomas Nelson",
"Three Sirens Press",
"Ticonderoga Publications",
"Time Inc.",
"Times Books",
"Titan Books",
"Top Shelf Productions",
"Tor Books",
"Triangle Books",
"Troubador Press",
"Tupelo Press",
"Tuttle Publishing",
"Twelveheads Press",
"Two Dollar Radio",
"U",
"UCL Press",
"United States Government Publishing Office",
"Universal Publishers (United States)",
"University of Akron Press",
"University of Alabama Press",
"University of Alaska Press",
"University of British Columbia Press",
"University of California Press",
"University of Chicago Press",
"University of Michigan Press",
"University of Minnesota Press",
"University of Nebraska Press",
"University of Pennsylvania Press",
"University of Queensland Press",
"University of South Carolina Press",
"University of Toronto Press",
"University of Wales Press",
"The University Press Limited",
"University Press of America",
"University Press of Kansas",
"University Press of Kentucky",
"Usborne Publishing",
"V",
"Valancourt Books",
"Velázquez Press",
"Verso Books",
"Victor Gollancz Ltd",
"Viking Press",
"Vintage Books",
"Virago Press",
"Virgin Books",
"Voyager Books",
"W",
"W. H. Allen & Co.",
"W. W. Norton & Company",
"Walter de Gruyter",
"Ward Lock & Co",
"WBusiness Books",
"Weidenfeld & Nicolson",
"Well-Trained Mind Press",
"Wesleyan University Press",
"WestBow Press",
"Westminster John Knox Press",
"Wildside Press",
"Wiley",
"William Edwin Rudge",
"William B. Eerdmans Publishing Company",
"Windgate Press",
"Wipf and Stock",
"Wisdom Publications",
"Witherby Publishing Group",
"Woodhead Publishing",
"Wordfarm",
"Workman Publishing Company",
"World Publishing Company",
"World Scientific",
"Wrecking Ball Press",
"Wrox Press",
"WSOY, Finland",
"X",
"Xoanon Publishing",
"Y",
"Yale University Press",
"Z",
"Zed Books",
"Ziff Davis",
"Zondervan"]
