export const genresList = new Set([
  "Acoustic",
  "Alternative",
  "Ambient",
  "Ballroom",
  "Blues",
  "Chamber Music",
  "Children's Music",
  "Classical",
  "Clubsounds",
  "Comedy & Spoken Word",
  "Contemporary Christian",
  "Country",
  "Dance & Electronica",
  "Disco",
  "Drama",
  "Easy Listening",
  "Electronic",
  "Folk",
  "Funk",
  "Gospel",
  "Hip-Hop & Soul",
  "Holiday",
  "House",
  "Hymns & Marches",
  "Jazz",
  "Karaoke",
  "Latin",
  "Metal",
  "Military",
  "Oldies",
  "Opera",
  "Pop",
  "Punk",
  "R&B & Soul",
  "Rap & Hip-Hop",
  "Reggae",
  "Religious & Devotional",
  "Rock",
  "Soul",
  "Sound Effects & Nature",
  "Soundtracks & Musicals",
  "Techno",
  "World Music",
  "Rap",
  "R&B"
]);
